
/*********************************************************************************************

    This is public domain software that was developed by or for the U.S. Naval Oceanographic
    Office and/or the U.S. Army Corps of Engineers.

    This is a work of the U.S. Government. In accordance with 17 USC 105, copyright protection
    is not available for any work of the U.S. Government.

    Neither the United States Government, nor any employees of the United States Government,
    nor the author, makes any warranty, express or implied, without even the implied warranty
    of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, or assumes any liability or
    responsibility for the accuracy, completeness, or usefulness of any information,
    apparatus, product, or process disclosed, or represents that its use would not infringe
    privately-owned rights. Reference herein to any specific commercial products, process,
    or service by trade name, trademark, manufacturer, or otherwise, does not necessarily
    constitute or imply its endorsement, recommendation, or favoring by the United States
    Government. The views and opinions of authors expressed herein do not necessarily state
    or reflect those of the United States Government, and shall not be used for advertising
    or product endorsement purposes.
*********************************************************************************************/


/****************************************  IMPORTANT NOTE  **********************************

    Comments in this file that start with / * ! or / / ! are being used by Doxygen to
    document the software.  Dashes in these comment blocks are used to create bullet lists.
    The lack of blank lines after a block of dash preceeded comments means that the next
    block of dash preceeded comments is a new, indented bullet list.  I've tried to keep the
    Doxygen formatting to a minimum but there are some other items (like <br> and <pre>)
    that need to be left alone.  If you see a comment that starts with / * ! or / / ! and
    there is something that looks a bit weird it is probably due to some arcane Doxygen
    syntax.  Be very careful modifying blocks of Doxygen comments.

*****************************************  IMPORTANT NOTE  **********************************/



#include "abe.hpp"


//  Set defaults for all of the program's user defined options.

void set_defaults (MISC *misc, OPTIONS *options)
{
  //  Tooltip text for the buttons that have editable accelerators.  If you want to change the order of the buttons
  //  change the define statements in abeDef.hpp

#ifdef NVWIN3X
  misc->progName[TRACKLINE] = "trackLine.exe";
  misc->progName[AREACHECK] = "areaCheck.exe";
  misc->progName[PFMLOAD] = "pfmLoad.exe";
  misc->progName[PFMVIEW] = "pfmView.exe";
  misc->progName[FILEEDIT3D] = "fileEdit3D.exe";
  misc->progName[PFMFEATURE] = "pfmFeature.exe";
  misc->progName[PFMEXTRACT] = "pfmExtract.exe";
  misc->progName[PFMGEOTIFF] = "pfmGeotiff.exe";
#else
  misc->progName[TRACKLINE] = "trackLine";
  misc->progName[AREACHECK] = "areaCheck";
  misc->progName[PFMLOAD] = "pfmLoad";
  misc->progName[PFMVIEW] = "pfmView";
  misc->progName[FILEEDIT3D] = "fileEdit3D";
  misc->progName[PFMFEATURE] = "pfmFeature";
  misc->progName[PFMEXTRACT] = "pfmExtract";
  misc->progName[PFMGEOTIFF] = "pfmGeotiff";
#endif

  misc->buttonIcon[TRACKLINE] = QIcon (":/icons/trackLine.png");
  misc->buttonIcon[AREACHECK] = QIcon (":/icons/areaCheck.png");
  misc->buttonIcon[PFMLOAD] = QIcon (":/icons/pfmLoad.png");
  misc->buttonIcon[PFMVIEW] = QIcon (":/icons/pfmView.png");
  misc->buttonIcon[FILEEDIT3D] = QIcon (":/icons/fileEdit3D.png");
  misc->buttonIcon[PFMFEATURE] = QIcon (":/icons/pfmFeature.png");
  misc->buttonIcon[PFMEXTRACT] = QIcon (":/icons/pfmExtract.png");
  misc->buttonIcon[PFMGEOTIFF] = QIcon (":/icons/pfmGeotiff.png");


  misc->buttonWhat[AREACHECK] =
    abe::tr ("The areaCheck program is used to display and edit ISS60 and generic area and zone files, "
             "Army Corps area files.  It can also be used to display track files generated by the trackLine "
             "program, GeoTIFF files, ESRI polygon shape files, Binary Feature Data (.bfd) files, LLZ files, "
             "YXZ files, CHRTR .fin files, and Open Navigation Surface (BAG) files.");
  misc->buttonWhat[PFMLOAD] =
    abe::tr ("The pfmLoad program is used to create, rebuild, or append to PFM structures.");
  misc->buttonWhat[PFMVIEW] =
    abe::tr ("The pfmView program is used to display geographically binned data that is stored in a PFM structure.  "
             "Subsequent to displaying a portion of the area, 2D or 3D editing of the contributing data points "
             "is done.  This program is what is most often referred to as the PFM Area-Based Editor.");
  misc->buttonWhat[FILEEDIT3D] =
    abe::tr ("The fileEdit3D program is used to display and edit data points in data files.  The currently "
             "available file types are Generic Sensor Format (GSF), CHARTS HOF, CHARTS TOF, CZMIL CPF, and ASPRS LAS.");
  misc->buttonWhat[PFMFEATURE] =
    abe::tr ("pfmFeature is a tool for selecting features in a PFM structure.  "
             "The selected features will be written to a new or pre-existing "
             "feature file.  Feature selection criteria may be either IHO special order or order 1.");
  misc->buttonWhat[PFMEXTRACT] =
    abe::tr ("The pfmExtract program is a tool for reading a PFM file and writing out a series of "
             "files (in SHAPE, ASCII, LLZ, or RDP format) for input to CARIS or other software packages.");
  misc->buttonWhat[PFMGEOTIFF] =
    abe::tr ("pfmGeotiff is a tool for creating a GeoTIFF file that represents one of "
             "the filtered surfaces of a PFM structure.  It can optionally write out "
             "multiple files that represent the data type coverages.");
  misc->buttonWhat[TRACKLINE] =
    abe::tr ("The trackLine program is used to create a decimated TRACK file from GSF, POS/SBET, "
             "or CZMIL CSF data files.  The TRACK file can be used in areaCheck to define an area for "
             "a PFM.");


  misc->buttonFile[TRACKLINE] = NVFalse;
  misc->buttonFile[AREACHECK] = NVTrue;
  misc->buttonFile[PFMLOAD] = NVFalse;
  misc->buttonFile[PFMVIEW] = NVTrue;
  misc->buttonFile[FILEEDIT3D] = NVTrue;
  misc->buttonFile[PFMFEATURE] = NVTrue;
  misc->buttonFile[PFMEXTRACT] = NVTrue;
  misc->buttonFile[PFMGEOTIFF] = NVTrue;


  options->buttonAccel[FILEEDIT3D] = "s";
  options->buttonAccel[TRACKLINE] = "t";
  options->buttonAccel[AREACHECK] = "a";
  options->buttonAccel[PFMLOAD] = "l";
  options->buttonAccel[PFMVIEW] = "v";
  options->buttonAccel[PFMFEATURE] = "f";
  options->buttonAccel[PFMEXTRACT] = "e";
  options->buttonAccel[PFMGEOTIFF] = "g";


  misc->qsettings_app = QString ("abe");

  options->window_x = 0;
  options->window_y = 0;

  options->main_button_icon_size = 48;
}
